// <auto-generated />
using System;
using GeeksBakery.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeeksBakery.Data.Migrations
{
    [DbContext(typeof(GeeksBakeryDbContext))]
    [Migration("20210711095922_addEntityConfiguration")]
    partial class addEntityConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeeksBakery.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "99e11e42-3d1d-4758-a206-82876c4a60cd",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d"),
                            ConcurrencyStamp = "3204a52e-7255-4d16-b803-226bb4edf788",
                            Description = "Customer role",
                            Name = "customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default-avatar.png");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dc5610e-e007-4e70-b01a-d46e039bf53b",
                            DoB = new DateTime(2000, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trung@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Pham Chi Trung",
                            NormalizedEmail = "trung@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEGRhXxxJlyoNWKby2leZXL3Nyz9nxcCZdjeHjsNAl7AYMVvObat3zimr04/6z1udLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("bff91064-dc92-421e-a233-d1080f630928"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41c39126-1f7a-4456-a2fd-00a40d70f93e",
                            DoB = new DateTime(2000, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Pham Chi Trung Customer",
                            NormalizedEmail = "customer1@gmail.com",
                            NormalizedUserName = "customer",
                            PasswordHash = "AQAAAAEAACcQAAAAEGmpNLDNzThqBCd7fxZJkVhVSqC0DFRTMhWGQv8B6hTH8A+aRoWeKASBvCIf3BG1Yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = new Guid("bff91054-dc92-421e-a233-d1080f630928"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1eefd838-92d6-4388-8cda-6817e8377219",
                            DoB = new DateTime(1996, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "David",
                            NormalizedEmail = "customer2@gmail.com",
                            NormalizedUserName = "customer",
                            PasswordHash = "AQAAAAEAACcQAAAAEDEuF3H619SlUMatVfl+0l8pyfUYDTzjTG8cpeLePqdXktW7BSCmLWZnCoOn7caf9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        });
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 39, DateTimeKind.Local).AddTicks(5092),
                            Description = "We kept this Classic cake untouched and unblemished because we feel it's perfect as it is. Baked with the richness of cocoa and lusciousness of fresh vanilla cream, topped with soft chocolate shavings and fresh cherries, this delicious cake will make you surrender to the zest forces of Sweet Indulgence. Savour the original taste of the all time classic- The Black Forest.",
                            Name = "Blackforest Cake With Cherries",
                            OriginalPrice = 200000m,
                            Price = 150000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6844),
                            Description = "Award yourself with this rich chocolate cake wonderfully crammed with Cadbury Fuse and white chocolate chunks and draped lusciously with molten chocolate.This perfect work of art hides in every bite, the scrumptious flavours of heavily whipped chocolate cream and nutty bits of chocolate that is a little nutty and a lot of tasty! ",
                            Name = "Snicker Fuse Chocolate Cake",
                            OriginalPrice = 250000m,
                            Price = 200000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6866),
                            Description = "An exceptionally creamy Open - layered Red Velvet cake with a topping that tastes like a MASH UP between the tropical fruits is truly a luxurious treat.Experience the richness and smoothness in this delicacy which is laden with kiwis, cherries,apples, dragon fruits and black grapes.Who said healthy and delicious are poles apart ?",
                            Name = "Red Velvet Fruit Layer Cake",
                            OriginalPrice = 260000m,
                            Price = 180000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6871),
                            Description = "This round chocolaty cake is the perfect treat for someone who is absolutely in love with chocolate cakes.This cake covered in rich chocolate ganache and decorated with chocolate shavings is the best gift one can have on their special day. ",
                            Name = "Chocolaty Creamy Round Cake",
                            OriginalPrice = 310000m,
                            Price = 290000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6873),
                            Description = "Any celebration is incomplete without this funfetti cake. Pipped with beautiful creamy decorations, this towering beauty is a grandiose deliciousness is sure to sweep everyone off their feet.And not just this, along with this beautify their day with extra sweetness and some extra colors with each bite topped with sumptuous confetti. ",
                            Name = "Rainbow Sprinkles Cake",
                            OriginalPrice = 400000m,
                            Price = 350000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6876),
                            Description = "A toothsome treat for the sugar lovers who are just passionate about chocolate and relish the mushiness of cake.Made of two layers of impossibly moist chocolate filled with mushy rich cream, this cake carries the enticing aroma of Vanilla and sumptuousness of chocolate.On top of it, the cake is garnished with handcrafted white and brown chocolate.Need I say more ? ",
                            Name = "Half Chocolate Half Vanilla Cake",
                            OriginalPrice = 170000m,
                            Price = 150000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6880),
                            Description = "This heart-shaped cake is nicely decorated with pink vanilla flavoured glazing and edible gems of vibrant colours like yellow, gold, red, blue, and white. The bonus of Cadbury chocolates and more gems comes when the hearty vanilla cake’s sweet crust is smashed.Note = Hammer will be given with the cake. ",
                            Name = "Hearty Choco Gems Pinata Cake",
                            OriginalPrice = 250000m,
                            Price = 200000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6882),
                            Description = "The heavenly taste of this Choco Truffle Cake will even leave the hardest-to - please chocolate addicts tranquil in every sense. Prepared with three layers of relishing chocolate cream filled in between the soft stacks of chocolate cake, and adorned with beautiful chocolate icing and rich glaze chocolate coating, this one is just irresistible. ",
                            Name = "Round Chocolate Truffle Cake",
                            OriginalPrice = 430000m,
                            Price = 350000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6885),
                            Description = "End the wait, break the ball with this black forest pinata cake, the true taste of surprise and luxury.It is a ball - shaped cake with a ball made of chocolate and a hammer that helps you break it loose. Next, what you see inside is a delicious black forest cake with icing, frosting and sponge, all chocolaty and mouth savouring.Make it your choice for all coming occasions.Note = Hammer will be given with the cake. ",
                            Name = "Birthday Black Forest Pinata Cake",
                            OriginalPrice = 200000m,
                            Price = 150000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6888),
                            Description = "Always and Forever Delight!This three layered moist and smooth cake filled with butterscotch chips and Vanilla cream is something not to be missed! Topped with Butterscotch glaze and brown chocolate flakes, adorned with scrumptious caramel dressing on the sides, it's time to feel the crunch! ",
                            Name = "Round Shape Butterscotch Cake",
                            OriginalPrice = 370000m,
                            Price = 290000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6891),
                            Description = "The two celebratory flavours in a single cake--red velvet cake layers entirely covered in dark chocolate cream roses sprinkled with red velvet crumbs.A slice of the cake won't be enough to celebrate the fusion of flavours; you would need a whole cake. ",
                            Name = "Heavenly Red Velvet Chocolate Cake",
                            OriginalPrice = 400000m,
                            Price = 350000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6893),
                            Description = "This cake is meant for all celebratory occasions! This three layered delicious pineapple flavoured cake filled with intensely whipped rich cream and pineapple fillings, perfectly defines simplicity at its best.Topped with pineapple slices, chocolate flakes and a further adorned with cherries, this cake is the perfect blend of sweetness and fluffiness. ",
                            Name = "Pineapple Cream Cake",
                            OriginalPrice = 230000m,
                            Price = 150000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6896),
                            Description = "The deliciousness of red velvet has been baked into the shape of a heart that resembles your sheer love and affection for your sweetheart. Tender, moist, and fluffy in texture, this captivating red velvet cake is a perfect sweet to cast the spell of love. ",
                            Name = "Heart Shape Red Velvet Cake",
                            OriginalPrice = 200000m,
                            Price = 180000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6898),
                            Description = "Freshly baked Vanilla cake, Whipped cream and bountiful tropical fruits come together to create a treat that is even tastier than it looks.This combination of whipped cream and fresh fruit is a perfect start for any celebration and an enticing end to any meal. ",
                            Name = "Assorted Fruit and Almond Cake",
                            OriginalPrice = 310000m,
                            Price = 260000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6902),
                            Description = "Another winning treat in your list of favorite items, a delicious Red Velvet cake with vanilla cream and icing, bedded red velvet ruling like a crown along with fragrant bread, the richest baked good.Greedy much, do remember to share the delicious deity with your loved ones and send some across to those you direly miss. ",
                            Name = "Red Velvet Buttercream Creamy Cake",
                            OriginalPrice = 280000m,
                            Price = 260000m,
                            Size = 20,
                            Stock = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 7, 11, 16, 59, 21, 40, DateTimeKind.Local).AddTicks(6904),
                            Description = "Both a joy to your sight as well as your taste buds, this pineapple flavoured scrumptious cake is a delight that you must indulge in every celebration!Frosted with pastel shades of buttercream, drizzling white chocolate ganache, and dollops of pink whipped cream on top, this delicious cake is loaded with copious amounts of gems in the center that spills out when you cut a slice! ",
                            Name = "Pineapple Gems Pinata Cake",
                            OriginalPrice = 250000m,
                            Price = 150000m,
                            Size = 20,
                            Stock = 1
                        });
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.CakeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CakeId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CakeId");

                    b.ToTable("CakeImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CakeId = 1,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "1.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CakeId = 1,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "1.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            CakeId = 1,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "1.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            CakeId = 1,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "1.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            CakeId = 2,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "2.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 6,
                            CakeId = 2,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "2.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            CakeId = 2,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "2.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            CakeId = 2,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "2.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            CakeId = 3,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "3.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CakeId = 3,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "3.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            CakeId = 3,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "3.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            CakeId = 3,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "3.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            CakeId = 4,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "4.1.jfif",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 14,
                            CakeId = 4,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "4.2.jfif",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 15,
                            CakeId = 4,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "4.3.jfif",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 16,
                            CakeId = 4,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "4.4.jfif",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CakeId = 5,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "5.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            CakeId = 5,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "5.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 19,
                            CakeId = 5,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "5.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 20,
                            CakeId = 5,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "5.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 21,
                            CakeId = 6,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "6.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 22,
                            CakeId = 6,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "6.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 23,
                            CakeId = 6,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "6.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            CakeId = 6,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "6.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 25,
                            CakeId = 7,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "7.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 26,
                            CakeId = 7,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "7.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 27,
                            CakeId = 8,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "8.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 28,
                            CakeId = 8,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "8.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 29,
                            CakeId = 8,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "8.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 30,
                            CakeId = 8,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "8.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 31,
                            CakeId = 9,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "9.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 32,
                            CakeId = 9,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "9.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 33,
                            CakeId = 9,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "9.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            CakeId = 10,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "10.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 35,
                            CakeId = 10,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "10.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 36,
                            CakeId = 10,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "10.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 37,
                            CakeId = 11,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "11.1.jfif",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 38,
                            CakeId = 11,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "11.2.jfif",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 39,
                            CakeId = 11,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "11.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 40,
                            CakeId = 12,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "12.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 41,
                            CakeId = 12,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "12.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 42,
                            CakeId = 12,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "12.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 43,
                            CakeId = 12,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "12.4.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 44,
                            CakeId = 13,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "13.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 45,
                            CakeId = 13,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "13.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 46,
                            CakeId = 14,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "14.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 47,
                            CakeId = 14,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "14.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 48,
                            CakeId = 14,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "14.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 49,
                            CakeId = 15,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "15.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 50,
                            CakeId = 15,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "15.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 51,
                            CakeId = 15,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "15.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 52,
                            CakeId = 16,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "16.1.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 53,
                            CakeId = 16,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "16.2.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 54,
                            CakeId = 16,
                            Caption = "Cake Images",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "16.3.jpg",
                            FileSize = 0L,
                            IsDefault = true,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Cart", b =>
                {
                    b.Property<int>("CakeId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CakeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Exotic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Backforest"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Butterscotch"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Vanilla"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Strawberry"
                        });
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2021, 5, 21, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 2,
                            DeliveryDate = new DateTime(2021, 5, 22, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 3,
                            DeliveryDate = new DateTime(2021, 5, 23, 9, 34, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 4,
                            DeliveryDate = new DateTime(2021, 5, 23, 16, 23, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 5,
                            Status = 2,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 6,
                            Status = 0,
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928")
                        });
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("CakeId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId", "CakeId");

                    b.HasIndex("CakeId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CakeId = 1,
                            Amount = 2
                        },
                        new
                        {
                            OrderId = 2,
                            CakeId = 2,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 3,
                            CakeId = 3,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 3,
                            CakeId = 1,
                            Amount = 2
                        },
                        new
                        {
                            OrderId = 4,
                            CakeId = 1,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 5,
                            CakeId = 3,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 5,
                            CakeId = 2,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 6,
                            CakeId = 4,
                            Amount = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        },
                        new
                        {
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928"),
                            RoleId = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d")
                        },
                        new
                        {
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928"),
                            RoleId = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Cake", b =>
                {
                    b.HasOne("GeeksBakery.Data.Entities.Category", "Category")
                        .WithMany("Cakes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.CakeImage", b =>
                {
                    b.HasOne("GeeksBakery.Data.Entities.Cake", "Cake")
                        .WithMany("CakeImages")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Cart", b =>
                {
                    b.HasOne("GeeksBakery.Data.Entities.Cake", "Cake")
                        .WithMany()
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeeksBakery.Data.Entities.AppUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Order", b =>
                {
                    b.HasOne("GeeksBakery.Data.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("GeeksBakery.Data.Entities.Cake", "Cake")
                        .WithMany()
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeeksBakery.Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Cake", b =>
                {
                    b.Navigation("CakeImages");
                });

            modelBuilder.Entity("GeeksBakery.Data.Entities.Category", b =>
                {
                    b.Navigation("Cakes");
                });
#pragma warning restore 612, 618
        }
    }
}
